version: '3.1'

services:
   db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: somewordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: raonis/wordpress-http-ssl:latest
     ports:
      - "80:80"
      - "443:443"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
